<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7EUDCAL" failures="3" tests="13" name="Test" time="0.103" errors="0" timestamp="2023-03-23T22:01:30 GMT-04:00">
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test1" time="0.011">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase.test1(MyTestCase.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test2" time="0.001"/>
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test3" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase.test3(MyTestCase.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase" name="test4" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Retry_Failed_Tests.RETRY_ANNOTATION_TRANSFORMER.MyTestCase.test4(MyTestCase.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- Test -->
